version: "3"
services:
  activemq:
    image: webcenter/activemq:latest
    expose:
    - "61616"
    ports:
    - "61616:61616"
    - "8161:8161"

  db:
    image: library/postgres:10
    ports:
    - "5432:5432"
    expose:
    - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  producer:
    image: no.marcello.example/producer:0.0.1-SNAPSHOT
    environment:
    - "SPRING_PROFILES_ACTIVE=docker"
    - "JAVA_OPTS=-Xmx256m -Xss256k"
    links:
    - "activemq"
    - "db"

  consumer:
    image: no.marcello.example/consumer:0.0.1-SNAPSHOT
    environment:
    - "SPRING_PROFILES_ACTIVE=docker"
    - "JAVA_OPTS=-Xmx256m -Xss256k"
    depends_on:
    - "producer"
    links:
    - "activemq"
    - "db"

  persister:
    image: no.marcello.example/persister:0.0.1-SNAPSHOT
    environment:
    - "SPRING_PROFILES_ACTIVE=docker"
    - "JAVA_OPTS=-Xmx256m -Xss256k"
    depends_on:
    - "producer"
    links:
    - "activemq"
    - "db"
