version: "3"
services:
  activemq:
    image: webcenter/activemq:latest
    expose:
    - "61616"
    ports:
    - "61616:61616"
    - "8161:8161"

  db:
    image: microsoft/mssql-server-linux:latest
    ports:
    - "1433:1433"
    expose:
    - "1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "S3cr3tpassw0rd"
