version: "3"
services:
  activemq:
    image: webcenter/activemq:latest
    expose:
    - "61616"
    ports:
    - "61616:61616"
    - "8161:8161"

  db:
    image: library/postgres:10
    ports:
    - "5432:5432"
    expose:
    - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
    - "8080:80"
    links:
    - "db"
