spring:
  application:
    name: persister
  datasource:
    url: jdbc:postgresql:testdb
    username: postgres
    password: postgres
    platform: postgres
  driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.use-new-id-generator-mappings: true
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

mq:
  url: failover:(tcp://0.0.0.0:61616)
